[tool.poetry]
name = "task_2"
version = "0.1.0"
description = ""
authors = ["Ilgiz Rakhimianov <i@rakhimianov.ru>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
