# Generated by Django 4.2.9 on 2024-02-05 01:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='наименование')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'топливо',
                'verbose_name_plural': 'топливо',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('currency', models.CharField(db_index=True, max_length=255, verbose_name='валюта')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stations', to='core.fuel', verbose_name='топливо')),
            ],
            options={
                'verbose_name': 'топливо в станции',
                'verbose_name_plural': 'топливо в станции',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='наименование')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'дополнительная услуга',
                'verbose_name_plural': 'дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('currency', models.CharField(db_index=True, max_length=255, verbose_name='валюта')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_stations', to='core.service', verbose_name='дополнительная услуга')),
            ],
            options={
                'verbose_name': 'дополнительная услуга в станции',
                'verbose_name_plural': 'дополнительные услуги в станции',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, verbose_name='внешний идентификатор')),
                ('number', models.CharField(db_index=True, max_length=255, verbose_name='номер')),
                ('address', models.TextField(blank=True, verbose_name='адрес')),
                ('coordinates', models.CharField(max_length=255, verbose_name='координаты')),
                ('fuels', models.ManyToManyField(blank=True, through='core.FuelStation', to='core.fuel')),
                ('services', models.ManyToManyField(blank=True, through='core.ServiceStation', to='core.service')),
            ],
            options={
                'verbose_name': 'заправочная станция',
                'verbose_name_plural': 'заправочные станции',
            },
        ),
        migrations.CreateModel(
            name='StationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, verbose_name='ссылка на изображение')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.station', verbose_name='заправочная станция')),
            ],
            options={
                'verbose_name': 'изображение заправочной станции',
                'verbose_name_plural': 'изображения заправочных станций',
            },
        ),
        migrations.AddField(
            model_name='servicestation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_stations', to='core.station', verbose_name='заправочная станция'),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stations', to='core.station', verbose_name='заправочная станция'),
        ),
    ]
