repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'
    hooks:
      - id: poetry-export
        args: ["--without", "test", "--without", "dev", "--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true